FROM python:3.8

WORKDIR /code

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

CMD ["/bin/bash", "-c", "/bin/sleep 5 && while true; do python ./src/check_news.py; sleep 3600; done"]